### ISSUE TITLE
Sandbox: Ephemera: Wrong caption for image

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#57]
The 'lunchtime play' image appears to have wrong caption. Just noticed. It seems to be fine in the excel sheet supplied though.

Correct caption for attached image: "Lunch time juxtapositions: Staff and students of NCBS gather for a lunch time cricket match. Adjacent to them (not seen), a student from Axel Brockmann’s group conducts an observational study of a beehive."

![8-ephemera-wrong-caption](https://cloud.githubusercontent.com/assets/4581081/19958330/6a8fc844-a1c4-11e6-8010-014c8d2490f7.png)

**Comment by khushpreet-kaur** [comment]
Caption is fixed now.

**Comment by salus-sage** [comment]
This commithas not fixed the issue - @shalinia  confirmed pulling the latest changes live
https://github.com/janastu/ncbs-ephemera/commit/906917bac50dd80dde5859715cbcec602089f06b

issue still not resolved, attached is the screenshot. 
https://www.ncbs.res.in/ncbs25/sandbox/ephemera/

![screenshot 17](https://cloud.githubusercontent.com/assets/6399323/20384292/4998ebb4-acd9-11e6-9fe6-e839eafd01a5.png)

**Comment by khushpreet-kaur** [comment]
@shalinia Please verify and close the issue, if resolved.

**Comment by vns2** [comment]
Resolved. Thanks!
